
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    env: 
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        persist-credentials: false
        cache: 'npm'
    - run: sudo npm ci
    - run: sudo npm run build --if-present

