
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    env: 
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}

    steps:
    - name: Fix Permissions
        run: |
          sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/cicd/cicd
          sudo chmod -R u+w /home/ubuntu/actions-runner/_work/cicd/cicd
    - name: Clean Workspace
        run: |
          sudo rm -rf /home/ubuntu/actions-runner/_work/cicd/cicd
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

